config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  devise_for :users
  # devise_for :users do
  get 'logout' => 'devise/sessions#destroy'
  # end
  root to: "pages#home"

  resources :users, only: [:show, :edit, :update]
  resources :adresses

end

app/models/adress.rb
class Adress < ActiveRecord::Base
  belongs_to :user
  has_many :water_counters
end

app/models/data_counter.rb
class DataCounter < ActiveRecord::Base
  belongs_to :water_counter
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :adresses

  validates :first_name, :second_name, presence: true, length: {maximum: 20}
end

app/models/water_counter.rb
class WaterCounter < ActiveRecord::Base
  belongs_to :adress
  has_many :data_counters
end

app/controllers/adresses_controller.rb
class AdressesController < ApplicationController
  before_action :set_adress, only: [:show, :edit, :update, :destroy]

  # GET /adresses
  def index
    @adresses = Adress.all
  end

  # GET /adresses/1
  def show
    @adress = Adress.find(params[:id])
  end

  # GET /adresses/new
  def new
    @adress = Adress.new
  end

  # GET /adresses/1/edit
  def edit
  end

  # POST /adresses
  def create
    @adress = Adress.new(adress_params)

    if @adress.save
      redirect_to @adress, notice: 'Adress was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /adresses/1
  def update
    if @adress.update(adress_params)
      redirect_to @adress, notice: 'Adress was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /adresses/1
  def destroy
    @adress.destroy
    redirect_to adresses_url, notice: 'Adress was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adress
      @adress = Adress.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def adress_params
      params[:adress]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  before_action :set_user, only: [:show, :edit, :update]

  # GET /users/1
  def show
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: I18n.t('controllers.users.updated')
    else
      render :edit
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:first_name, :second_name, :email)
    end
end

app/helpers/adresses_helper.rb
module AdressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/adresses/_form.html.erb
<%= simple_form_for(@adress) do |f| %>
  <% if @adress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adress.errors.count, "error") %> prohibited this adress from being saved:</h2>

      <ul>
      <% @adress.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      <%= f.input :city %>
      <%= f.input :street %>
      <%= f.input :home %>
      <%= f.input :description %>

    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adresses/edit.html.erb
<h1>Editing Adress</h1>

<%= render 'form' %>

<%= link_to 'Show', @adress %> |
<%= link_to 'Back', adresses_path %>

app/views/adresses/index.html.erb
<!--<p id="notice"><%= notice %></p>-->

<h1>Listing Adresses</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adresses.each do |adress| %>
      <tr>
        <td><%= link_to 'Show', adress %></td>
        <td><%= link_to 'Edit', edit_adress_path(adress) %></td>
        <td><%= link_to 'Destroy', adress, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adress', new_adress_path %>

app/views/adresses/new.html.erb
<h1>New Adress</h1>

<%= render 'form' %>

<%= link_to 'Back', adresses_path %>

app/views/adresses/show.html.erb
<p id="notice"><%= notice %></p>



<%= link_to 'Edit', edit_adress_path(@adress) %> |
<%= link_to 'Back', adresses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Upravdom" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top right">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to t('app.name'), root_path, class: 'navbar-brand' %>

        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
                <li><%= link_to 'Личный кабинет', current_user %></li>
                <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
            <% else %>
                <li><%= link_to 'Войти', new_user_session_path %></li>
                <li><%= link_to 'Зарегистрироваться', new_user_registration_path  %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <!--
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>
        </div>
        -->
      </div><!--/row-->

      <!--
      <footer>
        <p>&copy; <%= t('app.company') %> 2016</p>
      </footer>
      -->
    </div> <!-- /container -->

  </body>
</html>

app/views/pages/home.html.erb
<h1>Стартовая страница</h1>
<p>Тут будут отображатся различные новости</p>

app/views/partials/_form_errors.html.erb
<%# Универсальный паршиал отображения ошибок валидации любой модели %>
<% errors = model.errors %>

<% if errors.any? %>
    <div class="alert alert-danger">
      <div class="lead buffer-bottom">
        В вашей форме <%= errors.count %> <%= Russian.p(errors.count, 'ошибка', 'ошибки', 'ошибок') %>:
      </div>

      <ul>
        <% errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, 'error') %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="page-header">
  <h1>Редактирование профиля</h1>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h3><%= @user.first_name%> <%= @user.second_name %></h3>
<h3><%= @user.email %></h3>

<%= link_to 'Edit', edit_user_path(@user) %>
<%# <%= link_to 'Back', users_path %>